"""Original plain-language teaching guides; references point to original passages."""
GITA=[
('When you feel torn','Arjuna sees people he loves on both sides of the battle. He is upset and unsure what to do. The chapter lets us see his problem before anyone gives advice.','Say what is troubling you before trying to solve everything.','1.28–30','Feeling overwhelmed'),
('Do your part without making the result your whole identity','Krishna begins to answer Arjuna. One teaching is to act with steadiness in success and failure. This does not mean that results do not matter. It means a result need not decide your value as a person.','Prepare carefully. After the result, ask what you learned.','2.48','Fear of failure'),
('Work with care','Action cannot simply be avoided. Krishna speaks about doing the work that needs to be done without being driven only by personal gain.','Choose one responsibility you can complete today.','3.19','Avoiding a task'),
('Learn by asking good questions','Krishna explains action and knowledge. He also speaks about approaching a teacher with respect, questions and a willingness to learn.','Ask for an explanation of the part you do not understand.','4.34','Asking for help'),
('Look beyond labels','This chapter compares different ways of living and acting. A wise person sees beyond outward differences in people and living beings.','Notice whether a label is stopping you from treating someone fairly.','5.18','Judging others'),
('Bring your attention back','The mind wanders. Krishna describes bringing it back again and again. Wandering does not mean that practice has failed.','Work for a short stretch. When distracted, gently return to the next step.','6.26','Difficulty focusing'),
('Notice how things are connected','Krishna explains his relationship with the world. He uses the picture of jewels held together by a thread. The teaching has a devotional meaning; it also invites careful attention to connections.','Think about who helped make an ordinary part of your day possible.','7.7','Feeling disconnected'),
('Keep your values in mind while you act','Krishna speaks about remembrance and what we turn towards. He asks Arjuna to remember him and also carry out his work.','Before a difficult task, name the value you want your action to express.','8.7','Losing sight of priorities'),
('A small offering can carry love','Krishna speaks about devotion and receiving a leaf, flower, fruit or water offered with love. The teaching values the spirit of an offering.','Offer time, attention or a small kindness without comparing its price.','9.26','Feeling you have little to give'),
('Appreciate goodness without competing','Krishna describes many ways that excellence and power reflect the divine. These examples help Arjuna notice greatness throughout the world.','Admire a skill in someone else and learn from it rather than turning it into a contest.','10.41','Comparison'),
('Face the size of a difficult responsibility','Arjuna sees Krishna’s vast form. The vision includes wonder and fear. The chapter has a religious meaning that cannot be reduced to an ordinary work lesson.','When a task feels too big, identify your own part and the help you need.','11.32–33','A daunting responsibility'),
('Practise kindness in daily conduct','Krishna describes qualities of a devotee: not hating others, friendliness, compassion and steadiness. Devotion includes how a person treats others.','Pause before a sharp reply. Choose a response that is honest and kind.','12.13–14','Conflict'),
('Know yourself well enough to learn','The chapter distinguishes the body and experience from the one who knows them. It also lists qualities connected with knowledge, including humility and freedom from pretence.','Admit one thing you do not yet understand and ask a useful question about it.','13.8–12','Defensiveness'),
('Notice what is driving you','The three gunas are qualities discussed in the text: clarity, restless activity and dullness. They help describe patterns in experience, rather than fixed labels for someone’s worth.','Notice whether you need clearer thinking, a calmer pace or enough rest before acting.','14.5–9','Unhelpful habits'),
('Look for the roots of attachment','Krishna uses the image of an upside-down tree to describe worldly existence. It invites reflection on attachment and the search for a deeper foundation.','Ask whether a habit is serving you or whether you are holding it only because it is familiar.','15.1–4','Feeling stuck'),
('Build the qualities you want to live by','Krishna names qualities such as truthfulness, generosity, self-control and freedom from anger. He contrasts these with harmful patterns such as arrogance.','Choose one quality to practise in a small action today.','16.1–3','Changing behaviour'),
('Speak truth in a helpful way','This chapter discusses faith and different kinds of practice. It describes disciplined speech as truthful, helpful, pleasant and not needlessly upsetting.','Before giving feedback, say what happened and what would help, without insults.','17.15','A difficult conversation'),
('Reflect, then choose','The final chapter brings many teachings together. Krishna asks Arjuna to reflect fully and then act as he chooses. Learning supports responsibility rather than removing it.','Compare your realistic options, ask what you have missed, then choose one next step.','18.63','Difficulty taking decisions')]
BOOK_INTROS={
 'gita':'The Bhagavad Gita is a conversation between Arjuna and Krishna within the Mahabharata. Arjuna faces a painful decision. Their conversation explores action, learning, devotion and responsibility. Read the 18 chapters in order to follow how the discussion develops.',
 'bhagavatam':'The Bhagavatam tells stories of devotion, creation, kings, sages and Krishna. Stories often sit inside other conversations. Its 12 cantos are large divisions of the text. Read an episode in context before turning it into a lesson.',
 'narayaneeyam':'Narayaneeyam is Melpathur Narayana Bhattathiri’s devotional Sanskrit work associated with Guruvayur in Kerala. Its 100 dasakams retell themes and stories from the Bhagavatam. A dasakam is a short group of verses. The work also includes the poet’s prayers.',
 'shiva':'The Shiva Purana explores Shiva, devotion, worship and religious teaching through stories and conversations. This source describes seven samhitas, or major sections. The current import includes only the first section and portions numbered as section seven. The missing sections are not available here yet.',
 'vishnu':'Vishnu Sahasranamam is a hymn of names of Vishnu within the Mahabharata. A sahasranama is a collection of a thousand names. The names appear in groups within verses. Learn the meaning as well as the sound; different commentaries may explain a name in different ways.',
 'lalita':'Lalita Sahasranamam is a hymn of names of Lalita, a form of the Goddess. The names describe devotion and many aspects of the divine. Some meanings depend on a particular teaching tradition; those need context, rather than a quick literal word replacement.'}
SHIVA_READINGS={
 (1,1):('The sages ask how people can change','''At Prayaga, where the Ganga and Yamuna meet, a group of sages gathers for a long religious ceremony. Suta arrives. He is a student of Vyasa and a teller of Purana stories. The sages welcome him with respect.

They have listened to many teachings, but they still want to learn. Their question is about people living in troubled times. They describe dishonesty, greed, harm and the neglect of responsibilities. They are worried about how people can find a better way to live.

Their description reflects the social and religious assumptions of the text’s time. It includes harsh generalisations about groups of people. Reading it today does not require treating those generalisations as fair descriptions of people around us.

The sages ask Suta for a helpful path. Near the end, the chapter praises helping others. Suta remembers Shiva and prepares to answer. This chapter opens the conversation; it does not yet give the whole answer.

A useful way to read this opening is to notice the question: how can learning help people change their conduct? The sages seek guidance because they care about the wider community. That is a modern reading of the scene, rather than a literal instruction to follow every social judgement in the passage.'''),
 (1,2):('Suta introduces the Shiva Purana','''Suta welcomes the sages’ question and remembers his teacher. He introduces the Shiva Purana as a work that praises Shiva and supports devotion and religious understanding.

Much of this chapter praises the benefits of reading, hearing, copying and sharing the work. These statements belong to the devotional voice of the Purana. They are not a guarantee that reading a verse will automatically remove a person’s real-life responsibilities or the effects of harmful actions.

The chapter also explains the work’s arrangement. It discusses a larger earlier form, then describes a shorter version with seven major sections. It names Vidyeshvara, Rudra, Shatarudra, Kotirudra, Uma, Kailasa and Vayaviya. A samhita means a major section or collection.

This helps the reader understand that the Purana is a large work with different subjects and kinds of teaching. Reading it is more than collecting an isolated story or verse.

For a learner today, the practical next step is simple: choose a section, understand the setting, and read a little at a time. Ask what the passage says before deciding what lesson to take from it. That study method is our modern suggestion; the chapter itself is primarily an introduction and praise of the text.''')}
BOOK_INTROS.update({
 'agni':'The Agni Purana is a wide-ranging collection. Alongside religious stories and worship, it discusses subjects such as learning, buildings and public life. Its many subjects make it useful to read one chapter at a time rather than expect one continuous story.',
 'brahma':'The Brahma Purana includes accounts of creation, rulers, sacred places and devotion. Some chapters describe the importance of places of pilgrimage. A chapter’s setting matters: a pilgrimage account and a creation account serve different purposes.',
 'brahmanda':'The Brahmanda Purana includes descriptions of the universe, cycles of time, family lines and religious traditions. Brahmanda refers to the cosmic egg, an image used in accounts of the universe. Different versions and related sections need their own source details.',
 'brahmavaivarta':'The Brahmavaivarta Purana has sections associated with Brahma, Prakriti, Ganapati and Krishna’s birth and life. Prakriti means nature or the creative power discussed in the text. Read its stories within their devotional setting rather than assume every Purana tells them identically.',
 'bhavishya':'The Bhavishya Purana contains varied material, including worship, observances and narratives. Its versions differ substantially. The title’s connection with the future does not make every account a reliable prediction. The current collection has only selected chapters.',
 'garuda':'The Garuda Purana includes conversations associated with Vishnu and Garuda. It covers religious practice and many other subjects. Its discussions of death and the afterlife are one part of a much wider work; those passages need care and context, especially for children.',
 'kurma':'The Kurma Purana is named for Vishnu’s tortoise form. It includes accounts of creation, religious practice and teaching. Do not confuse the title of the whole work with only the tortoise episode in the churning story.',
 'linga':'The Linga Purana explores Shiva, creation, worship and religious teaching. The linga is a sacred form associated with Shiva. Its meaning needs the devotional context of the passage. Only Part I is in the present import.',
 'markandeya':'The Markandeya Purana includes stories, discussions and the Devi Mahatmya, a celebrated account of the Goddess. Its different narrative sections need to be read in context. The present electronic import is partial and has missing chapters.',
 'matsya':'The Matsya Purana is named for Vishnu’s fish form. It includes creation stories and subjects such as religious observance and sacred building traditions. The current source stops at chapter 176; the whole work is not available yet.',
 'narada':'The Narada Purana includes devotional and religious teaching, observances and descriptions of sacred places. Narada is a sage known for teaching and devotion. Follow the speaker and setting of each chapter before drawing a lesson.',
 'padma':'The Padma Purana is a very large work with several khandas, or major divisions. It includes stories, sacred places, devotion and religious practice. Different divisions and versions may have different emphases. The present collection contains selected chapters.',
 'skanda':'The Skanda Purana is a very large family of texts. Many sections describe sacred places and local traditions. The present source is Reva-khanda, associated with the Narmada region; it is not the whole Skanda Purana.',
 'vamana':'The Vamana Purana includes accounts connected with Shiva and Vishnu, sacred places and religious practice. Its title refers to Vishnu’s small or dwarf form. The current source contains chapters 1–69 and does not include every supplement.',
 'varaha':'The Varaha Purana is associated with Vishnu’s boar form and includes religious teaching, worship and sacred places. Read each chapter’s setting rather than assume every chapter tells the story of lifting the Earth.',
 'vishnu-purana':'The Vishnu Purana tells of creation, cycles of time, family lines and the life of Krishna within a devotional view centred on Vishnu. Its six books give a broad framework for the stories. The imported source is an electronic transcription, not an independently checked critical edition.'})
